package com.example.commons.equity.constants;

public interface KafkaConstants {
    String KAFKA_TOPIC_FUTURE_IN = "SDH_SVIL_JAR00_JARVIS_EQUITY_FUTURE-IN";
    String KAFKA_TOPIC_FUTURE_OUT = "SDH_SVIL_JAR00_JARVIS_EQUITY_FUTURE-OUT";
    String KAFKA_TOPIC_INDEX_IN = "SDH_SVIL_JAR00_JARVIS_EQUITY_INDEX-IN";
    String KAFKA_TOPIC_INDEX_OUT = "SDH_SVIL_JAR00_JARVIS_EQUITY_INDEX-OUT";
    String GROUP_ID = "groupID";
}
